#version: '3'
#services:
#    app:
#      container_name: shortener_url
#      build: .
#      ports:
#        - 9000:9000
#      restart: on-failure
#      volumes:
#        - api:/usr/src/app/
#      depends_on:
#        - fullstack-mysql
#      networks:
#        - fullstack
#
#
#  fullstack-mysql:
#    image: mysql:5.7
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_USER: mysql
#      MYSQL_PASSWORD: mysql-password
#      MYSQL_DATABASE: shortenurl
#      MYSQL_ROOT_PASSWORD: mysql-password
#    volumes:
#      - database_mysql:/var/lib/mysql
#    networks:
#      - fullstack
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin_container
#    depends_on:
#      - fullstack-mysql
#    environment:
#      PMA_HOST: fullstack-mysql # Note the "fullstack-mysql". Must be the name of the what you used as the mysql service.
#      MYSQL_ROOT_PASSWORD : mysql-password
#      PMA_PORT: 3306
#      PMA_PASSWORD: mysql-password
#    ports:
#      - 9090:80
#    restart: always
#    networks:
#      - fullstack
#
#
#volumes:
#  api:
#  database_mysql:
#
## Networks to be created to facilitate communication between containers
#networks:
#  fullstack:
#    driver: bridge
#

version: '3'
services:
  app:
    container_name: shorten-url
    build: .
    ports:
      - 9000:9000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack


  fullstack-mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql-password
      MYSQL_DATABASE: shortenurl
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql-password
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - fullstack-mysql
    environment:
      PMA_HOST: fullstack-mysql
      MYSQL_ROOT_PASSWORD: mysql-password
      PMA_PORT : 3306
    ports:
      - 9090:80
    restart: always
    networks:
      - fullstack


volumes:
  api:
  database_mysql:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
